server:
  port: 8088
logging:
  level:
    com.multiple.data.source.service.*: DEBUG

spring:
  application:
    name: hello-multiple-data-source
  datasource:
    master: 
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      username: test
      password: 123456
          #连接池类型改为druid
      type: com.alibaba.druid.pool.DruidDataSource
          #初始化连接数
      druid.initial-size: 10
          #最小连接数
      druid.min-idle: 100
          #最大连接数
      druid.max-active: 1000
          #获取连接时最大等待时间，单位毫秒
      druid.max-wait: 60000
          #检测连接是否有效
      druid.validation-query: SELECT 1 FROM DUAL
      druid.test-on-borrow: false
      druid.test-on-return: false
          #检查空闲连接有效性
      druid.test-while-idle: true
            #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      druid.time-between-eviction-runs-millis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
      druid.min-victable-idle-time-millis: 300000
           #查询超时时间 单位是毫秒
      druid.query-timeout: 60000
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录:单位秒
      spring.datasource.druid.connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    cluster: 
    - key: cluster
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/common?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: root
    cluster1: 
    - key: cluster1
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/demand_response?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: root
      
knife4j:
  # 是否开启加强模式 true开启  false关闭
  enable: true
  setting:
    # 是否开启调试功能  true开启  false关闭
    enableDebug: true
  basic:
    # 是否开启认证功能  true开启  false关闭
    enable: false
    username: test
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/**.xml